-- omg_smile_erp Veri Yedek / Aktarım Dosyası
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

-- Tablo: cariler (1 satır)
INSERT INTO "cariler" ("Klinik_Unvani", "Yetkili_Kisi", "Telefon", "Email", "Bakiye", "Risk_Limiti", "Indirim_Orani", "Sifre", "Adres", "Firma_Unvani", "Vergi_Dairesi", "Vergi_No", "IBAN", "Bildirim_Kurye", "Bildirim_Fatura", "Bildirim_Asama", "Otopilot_Kategori", "Otopilot_Islem", "Otopilot_Renk", "VIP_Seviye", "Durum") VALUES ('Dent 58', 'Hüseyin CEYLAN', '0554 733 4747', 'info@dent58.com', -5000.0, 50000.0, 0.0, '1234', 'Mehmet Ersoy Mah. 49-4 Sk. No:5/1A  Merkez/SİVAS', 'DENT 58 Ağız ve Diş Sağlığı Polikliniği', '-', '-', '-', 'WhatsApp', 'E-Posta', 'Sessiz (İstemiyorum)', '-', '-', 'A2', 'Platinum', 'Aktif') ON CONFLICT DO NOTHING;

-- Tablo: isler (2 satır)
INSERT INTO "isler" ("Tarih", "Klinik_Unvani", "Hasta_Adi", "Is_Turu", "Renk", "Asama", "Tutar_TL", "Sorumlu_Personel", "Harcanan_Malzeme", "Teslim_Tarihi", "Barkod", "Lot_Numarasi", "Sertifika_No", "Aciklama", "Adet", "Bakiye_Durumu", "Bakiye_Durumu2", "id", "Sinter_Sarfiyati", "Recine_Sarfiyati", "Metal_Tozu_Sarfiyati", "Fatura_Tarihi", "Iskonto", "Hasta_Kodu", "KDV_Orani") VALUES ('2026-05-09 16:27', 'Dent 58', 'Memnune Hanım', 'Multilayer Zirkonyum 5D Pro', 'A1', 'Tasarım Bekliyor', 0.0, 'Tamer Köseoğlu', 'CAM: BLK-0913 (1 Üye), Makine: Redon GTR, Top. 90 Dk (Takım başı 30 Dk)', '2026-05-09', 'OMG-0001', '-', '-', '-', 1, 'Bekliyor', 'Bekliyor', 1, '-', '-', '-', '-', 0.0, '-', 0.0) ON CONFLICT DO NOTHING;
INSERT INTO "isler" ("Tarih", "Klinik_Unvani", "Hasta_Adi", "Is_Turu", "Renk", "Asama", "Tutar_TL", "Sorumlu_Personel", "Harcanan_Malzeme", "Teslim_Tarihi", "Barkod", "Lot_Numarasi", "Sertifika_No", "Aciklama", "Adet", "Bakiye_Durumu", "Bakiye_Durumu2", "id", "Sinter_Sarfiyati", "Recine_Sarfiyati", "Metal_Tozu_Sarfiyati", "Fatura_Tarihi", "Iskonto", "Hasta_Kodu", "KDV_Orani") VALUES ('2026-05-21', 'Dent 58', 'Ayşe Hanım', 'Kafes İlavesi', 'A2', 'Teslim Edildi', 5000.0, 'Tamer Köseoğlu', 'CAM: BLK-2052 (11 Üye), Makine: Redon Hybrid, Top. 42 Dk (Takım başı 42 Dk)', '2026-05-21', 'OMG-0002', '00001', 'OMG-CERT-23548', '-', 1, 'Bekliyor', 'Bekliyor', 2, '-', '-', '-', '-', 0.0, '-', 0.0) ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('"isler"', 'id'), coalesce(max(id), 1), max(id) IS NOT null) FROM "isler";

-- Tablo: stok (111 satır)
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-5DML-12', 'BGS 5D ML 12mm', 'Zirkonyum Blok', 0.0, 'Adet', 4.0, 75.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-5DML-14', 'BGS 5D ML 14mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 80.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-5DML-16', 'BGS 5D ML 16mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 85.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-5DML-18', 'BGS 5D ML 18mm', 'Zirkonyum Blok', 21.0, 'Adet', 5.0, 90.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-5DML-20', 'BGS 5D ML 20mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 95.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-5DML-25', 'BGS 5D ML 25mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 100.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-4DML-12', 'BGS 4D ML 12mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 70.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-4DML-14', 'BGS 4D ML 14mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 75.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-4DML-16', 'BGS 4D ML 16mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 80.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-4DML-18', 'BGS 4D ML 18mm', 'Zirkonyum Blok', 2.0, 'Adet', 5.0, 85.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-4DML-20', 'BGS 4D ML 20mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 90.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-4DML-25', 'BGS 4D ML 25mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 95.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-3DPFS-12', 'BGS 3D PRO F.S 12mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 65.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-3DPFS-14', 'BGS 3D PRO F.S 14mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 70.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-3DPFS-16', 'BGS 3D PRO F.S 16mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 75.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-3DPFS-18', 'BGS 3D PRO F.S 18mm', 'Zirkonyum Blok', 36.0, 'Adet', 5.0, 80.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-3DPFS-20', 'BGS 3D PRO F.S 20mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 85.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-3DPFS-25', 'BGS 3D PRO F.S 25mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 90.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-3DPML-12', 'BGS 3D PRO ML 12mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 60.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-3DPML-14', 'BGS 3D PRO ML 14mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 65.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-3DPML-16', 'BGS 3D PRO ML 16mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 70.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-3DPML-18', 'BGS 3D PRO ML 18mm', 'Zirkonyum Blok', 8.0, 'Adet', 5.0, 75.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-3DPML-20', 'BGS 3D PRO ML 20mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 80.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-3DPML-25', 'BGS 3D PRO ML 25mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 85.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-3DML-12', 'BGS 3D ML 12mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 55.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-3DML-14', 'BGS 3D ML 14mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 60.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-3DML-16', 'BGS 3D ML 16mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 65.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-3DML-18', 'BGS 3D ML 18mm', 'Zirkonyum Blok', 2.0, 'Adet', 5.0, 70.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-3DML-20', 'BGS 3D ML 20mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 75.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-3DML-25', 'BGS 3D ML 25mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 80.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-STML-12', 'BGS ST ML 12mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 55.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-STML-14', 'BGS ST ML 14mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 60.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-STML-16', 'BGS ST ML 16mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 65.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-STML-18', 'BGS ST ML 18mm', 'Zirkonyum Blok', 2.0, 'Adet', 5.0, 70.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-STML-20', 'BGS ST ML 20mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 75.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-STML-25', 'BGS ST ML 25mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 80.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-STC-12', 'BGS ST-C 12mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 30.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-STC-14', 'BGS ST-C 14mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 35.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-STC-16', 'BGS ST-C 16mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 40.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-STC-18', 'BGS ST-C 18mm', 'Zirkonyum Blok', 2.0, 'Adet', 5.0, 45.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-STC-20', 'BGS ST-C 20mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 50.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-STC-25', 'BGS ST-C 25mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 55.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-UTC-12', 'BGS UT-C 12mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 30.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-UTC-14', 'BGS UT-C 14mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 35.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-UTC-16', 'BGS UT-C 16mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 40.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-UTC-18', 'BGS UT-C 18mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 45.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-UTC-20', 'BGS UT-C 20mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 50.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-UTC-25', 'BGS UT-C 25mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 55.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-SHT-12', 'BGS SHT 12mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 30.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-SHT-14', 'BGS SHT 14mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 35.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-SHT-16', 'BGS SHT 16mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 40.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-SHT-18', 'BGS SHT 18mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 45.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-SHT-20', 'BGS SHT 20mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 50.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-SHT-25', 'BGS SHT 25mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 55.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-ST-12', 'BGS ST 12mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 25.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-ST-14', 'BGS ST 14mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 30.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-ST-16', 'BGS ST 16mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 35.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-ST-18', 'BGS ST 18mm', 'Zirkonyum Blok', 2.0, 'Adet', 5.0, 40.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-ST-20', 'BGS ST 20mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 45.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-ST-25', 'BGS ST 25mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 50.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-UT-12', 'BGS UT 12mm ', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 25.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-UT-14', 'BGS UT 14mm ', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 30.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-UT-16', 'BGS UT 16mm ', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 35.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-UT-18', 'BGS UT 18mm ', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 40.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-UT-20', 'BGS UT 20mm ', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 45.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-UT-25', 'BGS UT 25mm ', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 50.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-HT-12', 'BGS HT 12mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 20.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-HT-14', 'BGS HT 14mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 25.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-HT-16', 'BGS HT 16mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 30.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-HT-18', 'BGS HT 18mm', 'Zirkonyum Blok', 2.0, 'Adet', 5.0, 35.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-HT-20', 'BGS HT 20mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 40.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('BGS-HT-25', 'BGS HT 25mm', 'Zirkonyum Blok', 0.0, 'Adet', 5.0, 45.0, 'Pasif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('T1', 'ø2.0 mm Zirconia Ball - Kaba Kesim', 'Frez', 1.0, 'Adet', 2.0, 0.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('T2', 'ø1.0 mm Zirconia Ball - Form Verme', 'Frez', 0.0, 'Adet', 2.0, 0.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('T3', 'ø0.6 mm Zirconia Ball - Detay/Fisür', 'Frez', 0.0, 'Adet', 2.0, 0.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('T4', 'ø2.0 mm Zirconia - Plastic/Wax', 'Frez', 0.0, 'Adet', 2.0, 0.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('T11', 'ø2.5 mm Glass Ceramic EDD', 'Frez', 0.0, 'Adet', 1.0, 0.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('T13', 'ø1.5 mm Glass Ceramic EDD', 'Frez', 0.0, 'Adet', 1.0, 0.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('T14', 'ø1.0 mm Glass Ceramic EDD', 'Frez', 0.0, 'Adet', 1.0, 0.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('T21', 'ø4.0 mm R1.0 Metal Kaba Boşaltma', 'Frez', 1.0, 'Adet', 1.0, 0.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('T22', 'ø2.5 mm R0.5 Metal Form Verme', 'Frez', 0.0, 'Adet', 1.0, 0.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('T30', 'ø0.6 mm Metal Hassas İşleme', 'Frez', 1.0, 'Adet', 1.0, 0.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('T36', 'T-Tool Özel Geometrik Kesici', 'Frez', 0.0, 'Adet', 1.0, 0.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('T5', 'ø1.0 mm Zirconia - Plastic/Wax', 'Frez', 0.0, 'Adet', 2.0, 0.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('T6', 'ø0.6 mm Zirconia - Plastic/Wax', 'Frez', 0.0, 'Adet', 2.0, 0.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('T7', 'ø0.3 mm Zirconia - Ultra İnce Detay', 'Frez', 0.0, 'Adet', 2.0, 0.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('T9', 'ø1.5 mm Zirconia Flat - Uzun Boy', 'Frez', 0.0, 'Adet', 2.0, 0.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('T10', 'ø1.5 mm Plastic/Wax - Uzun Flat', 'Frez', 0.0, 'Adet', 2.0, 0.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('T12', 'ø2.0 mm Flat - Kalibrasyon Frezi', 'Frez', 0.0, 'Adet', 1.0, 0.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('T15', 'ø1.0 mm Glass Ceramic EDD - Özel Geometri', 'Frez', 0.0, 'Adet', 1.0, 0.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('T16', 'ø0.6 mm Glass Ceramic EDD - Hassas Sonlandırma', 'Frez', 0.0, 'Adet', 1.0, 0.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('T20', 'ø1.5 mm Plastic/Wax - Uzun Ball', 'Frez', 0.0, 'Adet', 2.0, 0.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('T23', 'ø2.0 mm Metal İşleme', 'Frez', 0.0, 'Adet', 1.0, 0.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('T24', 'ø1.5 mm Metal İşleme', 'Frez', 0.0, 'Adet', 1.0, 0.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('T25', 'ø1.5 mm R0.2 Metal Detay', 'Frez', 0.0, 'Adet', 1.0, 0.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('T26', 'ø1.5 mm Flat - Metal', 'Frez', 0.0, 'Adet', 1.0, 0.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('T27', 'ø1.5 mm Long Flat - Metal', 'Frez', 0.0, 'Adet', 1.0, 0.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('T28', 'ø1.0 mm Flat - Metal', 'Frez', 0.0, 'Adet', 1.0, 0.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('T29', 'ø1.0 mm Ball - Metal', 'Frez', 0.0, 'Adet', 1.0, 0.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('T31', 'ø0.5 mm Metal Ultra İnce', 'Frez', 0.0, 'Adet', 1.0, 0.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('T32', 'ø0.3 mm Metal En Hassas Detay', 'Frez', 0.0, 'Adet', 1.0, 0.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('T33', 'ø0.3 mm Alternatif Metal Hassas', 'Frez', 0.0, 'Adet', 1.0, 0.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('T34', 'M2.0 Vida Diş Açma - Titanyum', 'Frez', 0.0, 'Adet', 1.0, 0.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('T35', 'M1.4 Vida Diş Açma - Titanyum', 'Frez', 0.0, 'Adet', 1.0, 0.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('T65-T66', 'Tek Ağızlı Özel Kesiciler (PMMA)', 'Frez', 0.0, 'Adet', 2.0, 0.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('SRF-01', 'İzolasyon Sıvısı', 'Sarf Malzeme', 5.0, 'Litre', 2.0, 150.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('SRF-02', 'Cila Patı', 'Sarf Malzeme', 10.0, 'Kutu', 3.0, 200.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('SRF-03', 'Modelleme Mumu', 'Sarf Malzeme', 20.0, 'Kutu', 5.0, 85.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('SRF-04', 'Kumlama Kumu (Alüminyum Oksit)', 'Sarf Malzeme', 50.0, 'Gram', 10.0, 120.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('SRF-05', 'Porselen Fırçası Seti', 'Sarf Malzeme', 5.0, 'Adet', 2.0, 450.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;
INSERT INTO "stok" ("Urun_Kodu", "Urun_Adi", "Kategori", "Mevcut_Miktar", "Birim", "Kritik_Sinir", "Satis_Fiyati", "Durum", "Renk", "Guncelleme_Tarihi", "Marka") VALUES ('SRF-06', 'Model Alçısı (Sert)', 'Sarf Malzeme', 25.0, 'Gram', 5.0, 300.0, 'Aktif', '-', '-', '-') ON CONFLICT DO NOTHING;

-- Tablo: giderler (3 satır)
INSERT INTO "giderler" ("Tarih", "Kategori", "Aciklama", "Tutar") VALUES ('2026-05-12', 'Kira', 'Nisan 2026 Kira ödemesi', 7000.0) ON CONFLICT DO NOTHING;
INSERT INTO "giderler" ("Tarih", "Kategori", "Aciklama", "Tutar") VALUES ('2026-05-13', 'Fatura/Bakım', 'Nisan 2026 Elektrik Faturası ödemesi', 5000.0) ON CONFLICT DO NOTHING;
INSERT INTO "giderler" ("Tarih", "Kategori", "Aciklama", "Tutar") VALUES ('2026-05-22', 'Yemek (Mutfak)', '2026 nisan ayı maliyeti', 4000.0) ON CONFLICT DO NOTHING;

-- Tablo: personeller (1 satır)
INSERT INTO "personeller" ("Ad_Soyad", "Gorevi", "Telefon", "Maas", "Baslama_Tarihi", "Ayrilma_Tarihi", "Durum", "Email", "Adres", "IBAN", "Kalan_Izin", "TC_No", "Foto_Yolu", "CV_Yolu") VALUES ('Tamer Köseoğlu', 'Teknik Ekip', '05413630504', 28075.0, '2026-05-07', '-', 'Aktif', 'tamerkoseoglu06@gmail.com', 'Ece Mah. Halil Rıfat Paşa Cd. İmren Evler  Apt. No: 30/2 Daire: 16 Merkez/ SİVAS', 'TR14 0004 6001 0588 8000 2295 72', 14, '69505128916', 'uploads/personel/fotolar\Tamer_Köseoğlu_WhatsApp Image 2019-08-23 at 18.47.41.jpeg', 'uploads/personel/cvler\Tamer_Köseoğlu_CV.pdf') ON CONFLICT DO NOTHING;

-- Tablo: kullanicilar (2 satır)
INSERT INTO "kullanicilar" ("Kullanici_Adi", "Sifre", "Rol") VALUES ('tamer', 'admin123', 'Admin') ON CONFLICT DO NOTHING;
INSERT INTO "kullanicilar" ("Kullanici_Adi", "Sifre", "Rol") VALUES ('kurye', '1234', 'Kurye') ON CONFLICT DO NOTHING;

-- Tablo: fiyat_listesi (53 satır)
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('Multilayer Zirkonyum 5D Pro', 'ZİRKONYUM/ FULL SERAMİK RESTARASYONLAR', 36.0, 'EUR') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('Multilayer Zirkonyum 3D Pro', 'ZİRKONYUM/ FULL SERAMİK RESTARASYONLAR', 30.0, 'EUR') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('Multilayer Zirkonyum 4D Pro', 'ZİRKONYUM/ FULL SERAMİK RESTARASYONLAR', 34.0, 'EUR') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('Zirkonyum Inley/Onlay', 'ZİRKONYUM/ FULL SERAMİK RESTARASYONLAR', 30.0, 'EUR') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('Oklüzal Vidalı Zirkonyum', 'ZİRKONYUM/ FULL SERAMİK RESTARASYONLAR', 40.0, 'EUR') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('İmplant Üzeri Zirkonyum', 'ZİRKONYUM/ FULL SERAMİK RESTARASYONLAR', 30.0, 'EUR') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('Monolitik Zirkonyum', 'ZİRKONYUM/ FULL SERAMİK RESTARASYONLAR', 30.0, 'EUR') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('Lazer Sinterleme Porselen', 'LAZER SİNTERLEME', 800.0, 'TL') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('Lazer Sinterleme İmplant Üstü Porselen', 'LAZER SİNTERLEME', 875.0, 'TL') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('Lazer Sinterleme Oklüzal Vidalı Porselen', 'LAZER SİNTERLEME', 1275.0, 'TL') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('Lazer Sinterleme Dolder Bar (Tek Çene)', 'LAZER SİNTERLEME', 2900.0, 'TL') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('Lazer Sinterleme Hibrit Bar (Tek Çene)', 'LAZER SİNTERLEME', 5300.0, 'TL') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('E.Max Full Kron', 'FULL SERAMİK RESTARASYONLAR', 60.0, 'EUR') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('E.Max Empress Laminate', 'FULL SERAMİK RESTARASYONLAR', 60.0, 'EUR') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('Empress Inlay/Onlay', 'FULL SERAMİK RESTARASYONLAR', 60.0, 'EUR') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('Kafes Döküm (Tek Çene)', 'İSKELET DÖKÜM PROTEZLER', 1100.0, 'TL') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('İskelet Protez Lazer Sinter (Tek Çene)', 'İSKELET DÖKÜM PROTEZLER', 1600.0, 'TL') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('Teleskop İskelet Protez Lazer Sinter (Tek Çene)', 'İSKELET DÖKÜM PROTEZLER', 1800.0, 'TL') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('Kafes İlavesi', 'İSKELET DÖKÜM PROTEZLER', 300.0, 'TL') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('Hassas Tutucu İskelet Lazer Sinter (Tek Çene)', 'İSKELET DÖKÜM PROTEZLER', 2000.0, 'TL') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('Pivo Döküm', 'İSKELET DÖKÜM PROTEZLER', 550.0, 'TL') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('Peek Bar (Tek Çene)', 'CAD/CAM MILLING', 200.0, 'EUR') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('Titanyum Bar (Tek Çene)', 'CAD/CAM MILLING', 300.0, 'EUR') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('Titanyum Toronto Milling (Tek Çene)', 'CAD/CAM MILLING', 350.0, 'EUR') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('Hi-Impact-Acrly Total (Tek Çene)', 'HAREKETLİ PROTEZLER', 2800.0, 'TL') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('Obturatör Total (Tek Çene)', 'HAREKETLİ PROTEZLER', 4500.0, 'TL') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('Total Protez Tek Çenebitim (Tek Çene)', 'HAREKETLİ PROTEZLER', 2750.0, 'TL') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('Parsiyel Protez Tek Çene Bitim (Tek Çene)', 'HAREKETLİ PROTEZLER', 2750.0, 'TL') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('Immediyat (Total Parsiyel) (Tek Çene)', 'HAREKETLİ PROTEZLER', 3200.0, 'TL') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('Işınlı Basplak (Tek Çene)', 'HAREKETLİ PROTEZLER', 200.0, 'TL') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('Yumuşak Beslenme Molloplast (Tek Çene)', 'HAREKETLİ PROTEZLER', 5300.0, 'TL') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('Işınlı Ölçü Kaşığı (Tek Çene)', 'HAREKETLİ PROTEZLER', 200.0, 'TL') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('Total Beslenme (Tek Çene)', 'HAREKETLİ PROTEZLER', 750.0, 'TL') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('Roch Köprü Protez (Tek Çene)', 'TAMİR PROTEZLER', 1650.0, 'TL') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('Cad/Cam Pmma Geçici Kron', 'TAMİR PROTEZLER', 150.0, 'TL') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('Cad/Cam Pmma Geçici İmmediat Yükleme', 'TAMİR PROTEZLER', 300.0, 'TL') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('3D Printer Tam Model (Tek Çene)', 'TAMİR PROTEZLER', 420.0, 'TL') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('Kapanış Geçicisi (Tek Çene)', 'TAMİR PROTEZLER', 900.0, 'TL') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('Diş İlavesi', 'TAMİR PROTEZLER', 550.0, 'TL') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('Porselen Tamiri', 'TAMİR PROTEZLER', 560.0, 'TL') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('3D Printer Geçici Kron', 'TAMİR PROTEZLER', 150.0, 'TL') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('3D Printer Yarım Model (Tek Çene)', 'TAMİR PROTEZLER', 280.0, 'TL') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('Splint', 'ORTODONTİK APAREYLER', 3000.0, 'TL') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('Aperey', 'ORTODONTİK APAREYLER', 1850.0, 'TL') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('Aperey Vidalı (1 adet vida)', 'ORTODONTİK APAREYLER', 3000.0, 'TL') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('Hareketli Yer Tutucu', 'ORTODONTİK APAREYLER', 1750.0, 'TL') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('Hollama Plağı', 'ORTODONTİK APAREYLER', 3250.0, 'TL') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('Sabit Yer Tutucu', 'ORTODONTİK APAREYLER', 1500.0, 'TL') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('Ölçü Döküm (Tek Çene)', 'ÖZEL İŞLEMLER', 75.0, 'TL') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('Mock-Up', 'ÖZEL İŞLEMLER', 125.0, 'TL') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('Pattern Resin (Tek Çene)', 'ÖZEL İŞLEMLER', 600.0, 'TL') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('Diş Eti İlavesi', 'ÖZEL İŞLEMLER', 1250.0, 'TL') ON CONFLICT DO NOTHING;
INSERT INTO "fiyat_listesi" ("Hizmet_Adi", "Kategori", "Fiyat", "Para_Birimi") VALUES ('Gece Plağı', 'ORTODONTİK APAREYLER', 750.0, 'TL') ON CONFLICT DO NOTHING;

-- Tablo: tahsilatlar (3 satır)
INSERT INTO "tahsilatlar" ("Tarih", "Klinik_Unvani", "Odeme_Turu", "Tutar", "Aciklama", "KDV_Orani") VALUES ('2026-05-22', 'Dent 58', 'Havale / EFT', 5000.0, '', NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tahsilatlar" ("Tarih", "Klinik_Unvani", "Odeme_Turu", "Tutar", "Aciklama", "KDV_Orani") VALUES ('2026-05-22', 'Dent 58', 'Havale / EFT', 2500.0, '', NULL) ON CONFLICT DO NOTHING;
INSERT INTO "tahsilatlar" ("Tarih", "Klinik_Unvani", "Odeme_Turu", "Tutar", "Aciklama", "KDV_Orani") VALUES ('2026-05-22', 'Dent 58', 'Havale / EFT', 2500.0, '', NULL) ON CONFLICT DO NOTHING;

-- Tablo: is_3d_modelleri (1 satır)
INSERT INTO "is_3d_modelleri" ("Is_ID", "Dosya_Yolu") VALUES (2, 'uploads\2026\05\Dent_58\Ayse_Hanim\STL_2_bar.stl') ON CONFLICT DO NOTHING;

-- Tablo: cihazlar (9 satır)
INSERT INTO "cihazlar" ("Cihaz_Adi", "Kategori", "Calisma_Saati", "Bakim_Siniri", "Son_Bakim_Tarihi", "Durum", "Gorsel_Yolu", "Haftalik_Hedef", "Aylik_Hedef", "Yillik_Hedef", "Guc_kW") VALUES ('Redon GTR', 'Kazıma Makinesi (Milling)', 0.0, 500.0, '2026-05-07', 'Aktif', 'uploads\cihazlar\141659_IMG20260413164458.jpg', '2026-05-14', '2026-06-06', '2027-04-14', 0.0) ON CONFLICT DO NOTHING;
INSERT INTO "cihazlar" ("Cihaz_Adi", "Kategori", "Calisma_Saati", "Bakim_Siniri", "Son_Bakim_Tarihi", "Durum", "Gorsel_Yolu", "Haftalik_Hedef", "Aylik_Hedef", "Yillik_Hedef", "Guc_kW") VALUES ('Redon HYBRID', 'Kazıma Makinesi (Milling)', 0.0, 500.0, '2026-04-14', 'Aktif', 'uploads\cihazlar\141824_IMG20260413164610.jpg', '2026-04-21', '2026-05-14', '2027-04-14', 0.0) ON CONFLICT DO NOTHING;
INSERT INTO "cihazlar" ("Cihaz_Adi", "Kategori", "Calisma_Saati", "Bakim_Siniri", "Son_Bakim_Tarihi", "Durum", "Gorsel_Yolu", "Haftalik_Hedef", "Aylik_Hedef", "Yillik_Hedef", "Guc_kW") VALUES ('BG-M150 (Metal Yazıcı)', '3D Yazıcı', 0.0, 500.0, '2026-04-14', 'Aktif', 'uploads\cihazlar\142038_IMG20260413164544.jpg', '2026-04-21', '2026-05-14', '2027-04-14', 0.0) ON CONFLICT DO NOTHING;
INSERT INTO "cihazlar" ("Cihaz_Adi", "Kategori", "Calisma_Saati", "Bakim_Siniri", "Son_Bakim_Tarihi", "Durum", "Gorsel_Yolu", "Haftalik_Hedef", "Aylik_Hedef", "Yillik_Hedef", "Guc_kW") VALUES ('Cameo CPD-100 3D print', '3D Yazıcı', 0.0, 500.0, '2026-04-14', 'Aktif', 'uploads\cihazlar\142327_IMG20260413164442.jpg', '2026-04-21', '2026-05-14', '2027-04-14', 0.0) ON CONFLICT DO NOTHING;
INSERT INTO "cihazlar" ("Cihaz_Adi", "Kategori", "Calisma_Saati", "Bakim_Siniri", "Son_Bakim_Tarihi", "Durum", "Gorsel_Yolu", "Haftalik_Hedef", "Aylik_Hedef", "Yillik_Hedef", "Guc_kW") VALUES ('Aidite CSF-400 PRO (Sinterleme Fırını)', 'Fırın (Sinter/Porselen)', 0.0, 500.0, '2026-04-14', 'Aktif', 'uploads\cihazlar\145650_IMG20260413164530.jpg', '2026-04-21', '2026-05-14', '2027-04-14', 0.0) ON CONFLICT DO NOTHING;
INSERT INTO "cihazlar" ("Cihaz_Adi", "Kategori", "Calisma_Saati", "Bakim_Siniri", "Son_Bakim_Tarihi", "Durum", "Gorsel_Yolu", "Haftalik_Hedef", "Aylik_Hedef", "Yillik_Hedef", "Guc_kW") VALUES ('Protherm Furnaces(Fırın)', 'Fırın (Sinter/Porselen)', 0.0, 500.0, '2026-04-14', 'Aktif', 'uploads\cihazlar\143256_IMG20260413164536.jpg', '2026-04-21', '2026-05-14', '2027-04-14', 0.0) ON CONFLICT DO NOTHING;
INSERT INTO "cihazlar" ("Cihaz_Adi", "Kategori", "Calisma_Saati", "Bakim_Siniri", "Son_Bakim_Tarihi", "Durum", "Gorsel_Yolu", "Haftalik_Hedef", "Aylik_Hedef", "Yillik_Hedef", "Guc_kW") VALUES ('Srefo Vacuum Annealing Furnaces', 'Fırın (Sinter/Porselen)', 0.0, 500.0, '2026-04-14', 'Aktif', 'uploads\cihazlar\143350_IMG20260413164618.jpg', '2026-04-21', '2026-05-14', '2027-04-14', 0.0) ON CONFLICT DO NOTHING;
INSERT INTO "cihazlar" ("Cihaz_Adi", "Kategori", "Calisma_Saati", "Bakim_Siniri", "Son_Bakim_Tarihi", "Durum", "Gorsel_Yolu", "Haftalik_Hedef", "Aylik_Hedef", "Yillik_Hedef", "Guc_kW") VALUES ('tds p200 porselen fırını', 'Fırın (Sinter/Porselen)', 0.0, 500.0, '2026-04-14', 'Aktif', 'uploads\cihazlar\150431_IMG20260413164653.jpg', '2026-04-21', '2026-05-14', '2027-04-14', 0.0) ON CONFLICT DO NOTHING;
INSERT INTO "cihazlar" ("Cihaz_Adi", "Kategori", "Calisma_Saati", "Bakim_Siniri", "Son_Bakim_Tarihi", "Durum", "Gorsel_Yolu", "Haftalik_Hedef", "Aylik_Hedef", "Yillik_Hedef", "Guc_kW") VALUES ('İvoclar-Programat P310 Seramik Fırını', 'Fırın (Sinter/Porselen)', 0.0, 500.0, '2026-04-14', 'Aktif', 'uploads\cihazlar\150542_IMG20260413164702.jpg', '2026-04-21', '2026-05-14', '2027-04-14', 0.0) ON CONFLICT DO NOTHING;

-- Tablo: cihaz_bakim_gecmisi (1 satır)
INSERT INTO "cihaz_bakim_gecmisi" ("Cihaz_Adi", "Tarih", "Islem", "Maliyet", "Aciklama") VALUES ('Redon GTR', '2026-05-07', 'Spindle İçi Havayla Temizlendi | ATC Yuvaları Kontrol Edildi', 0.0, 'Sistem Onaylı') ON CONFLICT DO NOTHING;

-- Tablo: kurye_islemleri (1 satır)
INSERT INTO "kurye_islemleri" ("Tarih", "Saat", "Klinik_Unvani", "Aciklama", "Durum") VALUES ('2026-05-21', '17:37', 'Dent 58', '1 adet ölçü', 'Teslim Alındı (Laboratuvara Geldi)') ON CONFLICT DO NOTHING;

-- Tablo: cam_bloklar (4 satır)
INSERT INTO "cam_bloklar" ("Blok_Kodu", "Urun_Adi", "Boyut_Renk", "Kapasite_Uye", "Kalan_Uye", "Durum") VALUES ('BLK-0913', 'BGS 5D ML 18mm', 'A2 18mm', 26, 8, 'Yarım') ON CONFLICT DO NOTHING;
INSERT INTO "cam_bloklar" ("Blok_Kodu", "Urun_Adi", "Boyut_Renk", "Kapasite_Uye", "Kalan_Uye", "Durum") VALUES ('BLK-2052', 'BGS 5D ML 18mm', 'A1 18 mm', 22, 11, 'Yarım') ON CONFLICT DO NOTHING;
INSERT INTO "cam_bloklar" ("Blok_Kodu", "Urun_Adi", "Boyut_Renk", "Kapasite_Uye", "Kalan_Uye", "Durum") VALUES ('BLK-3730', 'BGS 5D ML 18mm', '', 22, 22, 'Yarım') ON CONFLICT DO NOTHING;
INSERT INTO "cam_bloklar" ("Blok_Kodu", "Urun_Adi", "Boyut_Renk", "Kapasite_Uye", "Kalan_Uye", "Durum") VALUES ('BLK-3734', 'BGS 5D ML 18mm', '', 22, 22, 'Yarım') ON CONFLICT DO NOTHING;

-- Tablo: cam_frezler (3 satır)
INSERT INTO "cam_frezler" ("Frez_Kodu", "Urun_Adi", "Uyumlu_Makine", "Max_Omur_Dk", "Kalan_Omur_Dk", "Durum") VALUES ('FRZ-5718', 'ø2.0 mm Zirconia Ball - Kaba Kesim', 'Redon GTR', 2000, 1940, 'Aktif') ON CONFLICT DO NOTHING;
INSERT INTO "cam_frezler" ("Frez_Kodu", "Urun_Adi", "Uyumlu_Makine", "Max_Omur_Dk", "Kalan_Omur_Dk", "Durum") VALUES ('FRZ-5338', 'ø1.0 mm Zirconia Ball - Form Verme', 'Redon GTR', 2000, 1985, 'Aktif') ON CONFLICT DO NOTHING;
INSERT INTO "cam_frezler" ("Frez_Kodu", "Urun_Adi", "Uyumlu_Makine", "Max_Omur_Dk", "Kalan_Omur_Dk", "Durum") VALUES ('FRZ-5343', 'ø0.6 mm Zirconia Ball - Detay/Fisür', 'Redon GTR', 2000, 1985, 'Aktif') ON CONFLICT DO NOTHING;

-- Tablo: sistem_ayarlari (1 satır)
INSERT INTO "sistem_ayarlari" ("Ayar_Adi", "Deger") VALUES ('Lisans_Durumu', 'PRO') ON CONFLICT DO NOTHING;

-- Tablo: ayarlar (11 satır)
INSERT INTO "ayarlar" ("Ayar_Adi", "Ayar_Degeri") VALUES ('Barkod_Onek', 'OMG') ON CONFLICT DO NOTHING;
INSERT INTO "ayarlar" ("Ayar_Adi", "Ayar_Degeri") VALUES ('Para_Birimi', 'TL') ON CONFLICT DO NOTHING;
INSERT INTO "ayarlar" ("Ayar_Adi", "Ayar_Degeri") VALUES ('KDV_Orani', '20') ON CONFLICT DO NOTHING;
INSERT INTO "ayarlar" ("Ayar_Adi", "Ayar_Degeri") VALUES ('Sms_Sessiz_Saatler', '22:00 - 08:00') ON CONFLICT DO NOTHING;
INSERT INTO "ayarlar" ("Ayar_Adi", "Ayar_Degeri") VALUES ('Kurye_Sablonu', 'Sayın [Hekim_Adı],
Kurye talebiniz alınmıştır. Kuryemiz en kısa sürede adresinize yönlendirilecektir.
Teşekkür ederiz.') ON CONFLICT DO NOTHING;
INSERT INTO "ayarlar" ("Ayar_Adi", "Ayar_Degeri") VALUES ('Lobi_IP', '192.168.1.100') ON CONFLICT DO NOTHING;
INSERT INTO "ayarlar" ("Ayar_Adi", "Ayar_Degeri") VALUES ('Kurumsal_Logo', 'uploads/kurumsal\sistem_logosu_163837.png') ON CONFLICT DO NOTHING;
INSERT INTO "ayarlar" ("Ayar_Adi", "Ayar_Degeri") VALUES ('Elektrik_kWh_Fiyati', '3.0') ON CONFLICT DO NOTHING;
INSERT INTO "ayarlar" ("Ayar_Adi", "Ayar_Degeri") VALUES ('Uretim_Disi_Maliyet', '0') ON CONFLICT DO NOTHING;
INSERT INTO "ayarlar" ("Ayar_Adi", "Ayar_Degeri") VALUES ('Manuel_Euro_Kuru', '55.0683') ON CONFLICT DO NOTHING;
INSERT INTO "ayarlar" ("Ayar_Adi", "Ayar_Degeri") VALUES ('Kur_Guncelleme_Saati', '1970-01-01 00:00') ON CONFLICT DO NOTHING;

-- Tablo: laboratuvar_dokumanlari (2 satır)
INSERT INTO "laboratuvar_dokumanlari" ("Tarih", "Dokuman_Adi", "Dosya_Yolu", "Dosya_Turu") VALUES ('2026-04-25', '2026 Ürün Kataloğu', 'uploads/dokumanlar\Omg Smile Dijital Katalog.pdf', 'application/pdf') ON CONFLICT DO NOTHING;
INSERT INTO "laboratuvar_dokumanlari" ("Tarih", "Dokuman_Adi", "Dosya_Yolu", "Dosya_Turu") VALUES ('2026-04-25', 'deneme', 'uploads/dokumanlar\Omg Smile - Dijital Ekosistem.pdf', 'application/pdf') ON CONFLICT DO NOTHING;

-- Tablo: sistem_loglari (3 satır)
INSERT INTO "sistem_loglari" ("Tarih_Saat", "Kullanici", "Aksiyon", "Goruldu") VALUES ('14:37', 'DenemeKlinik', 'Yeni bir reçete oluşturdu.', 1) ON CONFLICT DO NOTHING;
INSERT INTO "sistem_loglari" ("Tarih_Saat", "Kullanici", "Aksiyon", "Goruldu") VALUES ('14:37', 'DenemeKlinik', 'Yeni bir reçete oluşturdu.', 1) ON CONFLICT DO NOTHING;
INSERT INTO "sistem_loglari" ("Tarih_Saat", "Kullanici", "Aksiyon", "Goruldu") VALUES ('14:38', 'DenemeKlinik', 'Yeni bir reçete oluşturdu.', 1) ON CONFLICT DO NOTHING;

-- Tablo: mesajlar (28 satır)
INSERT INTO "mesajlar" ("Tarih_Saat", "Gonderen", "Alici", "Mesaj", "Okundu") VALUES ('16:41', 'Laboratuvar (Sen)', 'Genel', 'selam hocam', 0) ON CONFLICT DO NOTHING;
INSERT INTO "mesajlar" ("Tarih_Saat", "Gonderen", "Alici", "Mesaj", "Okundu") VALUES ('17:51', 'Laboratuvar (Sen)', 'Genel', 'nasılsın', 0) ON CONFLICT DO NOTHING;
INSERT INTO "mesajlar" ("Tarih_Saat", "Gonderen", "Alici", "Mesaj", "Okundu") VALUES ('19:05', 'Laboratuvar (Sen)', 'Genel', 'deneme', 0) ON CONFLICT DO NOTHING;
INSERT INTO "mesajlar" ("Tarih_Saat", "Gonderen", "Alici", "Mesaj", "Okundu") VALUES ('19:05', 'Laboratuvar (Sen)', 'Genel', 'hocam', 0) ON CONFLICT DO NOTHING;
INSERT INTO "mesajlar" ("Tarih_Saat", "Gonderen", "Alici", "Mesaj", "Okundu") VALUES ('19:26', 'Laboratuvar (Sen)', 'Genel', 'selam', 0) ON CONFLICT DO NOTHING;
INSERT INTO "mesajlar" ("Tarih_Saat", "Gonderen", "Alici", "Mesaj", "Okundu") VALUES ('22:47', 'Bilinmeyen Kullanıcı', 'Genel', 'deneme', 0) ON CONFLICT DO NOTHING;
INSERT INTO "mesajlar" ("Tarih_Saat", "Gonderen", "Alici", "Mesaj", "Okundu") VALUES ('22:48', 'Bilinmeyen Kullanıcı', 'Genel', 'merhaba', 0) ON CONFLICT DO NOTHING;
INSERT INTO "mesajlar" ("Tarih_Saat", "Gonderen", "Alici", "Mesaj", "Okundu") VALUES ('22:49', 'Bilinmeyen Kullanıcı', 'Genel', 'ben geldim', 0) ON CONFLICT DO NOTHING;
INSERT INTO "mesajlar" ("Tarih_Saat", "Gonderen", "Alici", "Mesaj", "Okundu") VALUES ('23:02', 'Bilinmeyen Kullanıcı', 'Genel', 'selam', 0) ON CONFLICT DO NOTHING;
INSERT INTO "mesajlar" ("Tarih_Saat", "Gonderen", "Alici", "Mesaj", "Okundu") VALUES ('23:17', 'tamer', 'Genel', 'deneme', 0) ON CONFLICT DO NOTHING;
INSERT INTO "mesajlar" ("Tarih_Saat", "Gonderen", "Alici", "Mesaj", "Okundu") VALUES ('23:18', 'ayse', 'Genel', 'anlaştık', 0) ON CONFLICT DO NOTHING;
INSERT INTO "mesajlar" ("Tarih_Saat", "Gonderen", "Alici", "Mesaj", "Okundu") VALUES ('23:19', 'tamer', 'Genel', 'dent58 burda mısın hocam', 0) ON CONFLICT DO NOTHING;
INSERT INTO "mesajlar" ("Tarih_Saat", "Gonderen", "Alici", "Mesaj", "Okundu") VALUES ('23:19', 'Dent58', 'Genel', 'burdayım tamer', 0) ON CONFLICT DO NOTHING;
INSERT INTO "mesajlar" ("Tarih_Saat", "Gonderen", "Alici", "Mesaj", "Okundu") VALUES ('23:28', 'tamer', 'Genel', 'tamam hocam', 0) ON CONFLICT DO NOTHING;
INSERT INTO "mesajlar" ("Tarih_Saat", "Gonderen", "Alici", "Mesaj", "Okundu") VALUES ('23:29', 'tamer', 'Genel', 'ayşe', 0) ON CONFLICT DO NOTHING;
INSERT INTO "mesajlar" ("Tarih_Saat", "Gonderen", "Alici", "Mesaj", "Okundu") VALUES ('23:34', 'tamer', 'Genel', '🚨 [ACİL] Lütfen acil dönüş yapın! Hasta bekliyor.', 0) ON CONFLICT DO NOTHING;
INSERT INTO "mesajlar" ("Tarih_Saat", "Gonderen", "Alici", "Mesaj", "Okundu") VALUES ('23:34', 'tamer', 'Genel', '✅ İşlem onaylandı, üretime geçiliyor.', 0) ON CONFLICT DO NOTHING;
INSERT INTO "mesajlar" ("Tarih_Saat", "Gonderen", "Alici", "Mesaj", "Okundu") VALUES ('23:34', 'tamer', 'Genel', '📎 [MEDYA] Röntgen/Fotoğraf eklendi.', 0) ON CONFLICT DO NOTHING;
INSERT INTO "mesajlar" ("Tarih_Saat", "Gonderen", "Alici", "Mesaj", "Okundu") VALUES ('23:41', 'tamer', 'Genel', '📎 [MEDYA] Röntgen/Fotoğraf eklendi.', 0) ON CONFLICT DO NOTHING;
INSERT INTO "mesajlar" ("Tarih_Saat", "Gonderen", "Alici", "Mesaj", "Okundu") VALUES ('23:41', 'tamer', 'Genel', '🚨 [ACİL] Lütfen acil dönüş yapın! Hasta bekliyor.', 0) ON CONFLICT DO NOTHING;
INSERT INTO "mesajlar" ("Tarih_Saat", "Gonderen", "Alici", "Mesaj", "Okundu") VALUES ('00:04', 'tamer', 'Laboratuvar', 'selam', 0) ON CONFLICT DO NOTHING;
INSERT INTO "mesajlar" ("Tarih_Saat", "Gonderen", "Alici", "Mesaj", "Okundu") VALUES ('00:05', 'Dent58', 'Laboratuvar', 'selam ', 0) ON CONFLICT DO NOTHING;
INSERT INTO "mesajlar" ("Tarih_Saat", "Gonderen", "Alici", "Mesaj", "Okundu") VALUES ('00:14', 'tamer', 'Laboratuvar', '🚨 [ACİL] Lütfen acil dönüş yapın! Hasta bekliyor.', 0) ON CONFLICT DO NOTHING;
INSERT INTO "mesajlar" ("Tarih_Saat", "Gonderen", "Alici", "Mesaj", "Okundu") VALUES ('00:15', 'Dent58', 'Laboratuvar', 'selam', 0) ON CONFLICT DO NOTHING;
INSERT INTO "mesajlar" ("Tarih_Saat", "Gonderen", "Alici", "Mesaj", "Okundu") VALUES ('00:15', 'Dent58', 'Laboratuvar', '🚨 [ACİL] Lütfen acil dönüş yapın! Hasta bekliyor.', 0) ON CONFLICT DO NOTHING;
INSERT INTO "mesajlar" ("Tarih_Saat", "Gonderen", "Alici", "Mesaj", "Okundu") VALUES ('00:16', 'ayse', 'Laboratuvar', 'tamer', 0) ON CONFLICT DO NOTHING;
INSERT INTO "mesajlar" ("Tarih_Saat", "Gonderen", "Alici", "Mesaj", "Okundu") VALUES ('00:18', 'tamer', 'Laboratuvar', '✅ İşlem onaylandı, üretime geçiliyor.', 0) ON CONFLICT DO NOTHING;
INSERT INTO "mesajlar" ("Tarih_Saat", "Gonderen", "Alici", "Mesaj", "Okundu") VALUES ('13:11', 'tamer', 'Laboratuvar', '📎 [MEDYA] Röntgen/Fotoğraf eklendi.', 0) ON CONFLICT DO NOTHING;

-- Tablo: aktif_frezler (7 satır)
INSERT INTO "aktif_frezler" ("id", "makine_adi", "yuva_no", "frez_kod", "toplam_omur_dk", "kullanilan_dk", "birim_fiyat_euro", "durum", "frez_adi") VALUES (1, 'Redon GTR', 'M1', 'FRZ-0634', 1500, 0, 0.0, 'Ömrü Doldu', NULL) ON CONFLICT DO NOTHING;
INSERT INTO "aktif_frezler" ("id", "makine_adi", "yuva_no", "frez_kod", "toplam_omur_dk", "kullanilan_dk", "birim_fiyat_euro", "durum", "frez_adi") VALUES (2, 'Redon GTR', '-', 'FRZ-0724', 1500, 0, 0.0, 'Ömrü Doldu', NULL) ON CONFLICT DO NOTHING;
INSERT INTO "aktif_frezler" ("id", "makine_adi", "yuva_no", "frez_kod", "toplam_omur_dk", "kullanilan_dk", "birim_fiyat_euro", "durum", "frez_adi") VALUES (3, 'Redon GTR', '-', 'FRZ-1916', 1500, 0, 0.0, 'Ömrü Doldu', NULL) ON CONFLICT DO NOTHING;
INSERT INTO "aktif_frezler" ("id", "makine_adi", "yuva_no", "frez_kod", "toplam_omur_dk", "kullanilan_dk", "birim_fiyat_euro", "durum", "frez_adi") VALUES (4, 'Redon Hybrid', 'M2', 'FRZ-T4-1154', 1500, 0, 0.0, 'Ömrü Doldu', 'ø2.0 mm Zirconia - Plastic/Wax') ON CONFLICT DO NOTHING;
INSERT INTO "aktif_frezler" ("id", "makine_adi", "yuva_no", "frez_kod", "toplam_omur_dk", "kullanilan_dk", "birim_fiyat_euro", "durum", "frez_adi") VALUES (5, 'Redon Hybrid', 'M3', 'FRZ-T1-0918', 1500, 72, 0.0, 'Aktif', 'ø2.0 mm Zirconia Ball - Kaba Kesim') ON CONFLICT DO NOTHING;
INSERT INTO "aktif_frezler" ("id", "makine_adi", "yuva_no", "frez_kod", "toplam_omur_dk", "kullanilan_dk", "birim_fiyat_euro", "durum", "frez_adi") VALUES (6, 'Redon GTR', 'M2', 'FRZ-T2-0937', 1500, 30, 0.0, 'Aktif', 'ø1.0 mm Zirconia Ball - Form Verme') ON CONFLICT DO NOTHING;
INSERT INTO "aktif_frezler" ("id", "makine_adi", "yuva_no", "frez_kod", "toplam_omur_dk", "kullanilan_dk", "birim_fiyat_euro", "durum", "frez_adi") VALUES (7, 'Redon GTR', 'M3', 'FRZ-T3-0944', 1500, 30, 0.0, 'Aktif', 'ø0.6 mm Zirconia Ball - Detay/Fisür') ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('"aktif_frezler"', 'id'), coalesce(max(id), 1), max(id) IS NOT null) FROM "aktif_frezler";

-- Tablo: kullanici_aktiviteleri (1 satır)
INSERT INTO "kullanici_aktiviteleri" ("id", "Kullanici_Adi", "Rol", "Tarih", "Son_Aktivite_Zamani", "Toplam_Aktif_Saniye") VALUES (1, 'tamer', 'Admin', '2026-08-11', '2026-08-11 16:56:58', 56) ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('"kullanici_aktiviteleri"', 'id'), coalesce(max(id), 1), max(id) IS NOT null) FROM "kullanici_aktiviteleri";

